### ISSUE TITLE
Fix package names for gson.* and http.*

### ISSUE THREAD

**Issue by dhinus** [contactlab/contacthub-sdk-java#68]
[Trello card](https://trello.com/c/58b7f35eda7d0b6cb3068ce4/)

## description
The package names for classes in the folders `internal/gson` and `internal/http` are wrong (they don't include `internal` in the package name)

## specs
Modify the package names in `ContactHubGson.java` and `Request.java`:

* `it.contactlab.hub.sdk.java.gson` -> `it.contactlab.hub.sdk.java.internal.gson`
* `it.contactlab.hub.sdk.java.http` -> `it.contactlab.hub.sdk.java.internal.http`

## misc

**Comment by psantori** [comment]
Fixed by pr 85
