### ISSUE TITLE
Add LIKE field in the Operator enum

### ISSUE THREAD

**Issue by Ema-jar** [contactlab/contacthub-sdk-java#99]
[Trello card](https://trello.com/c/5b27adc2b07bdf653aaa3c72/)

We need the `LIKE` field in the `Operator` enum, in order to create a query condition like this:
```
{
    "type": "atomic",
    "attribute": "base.lastName",
    "operator": "LIKE",
    "value": "LastName"
}
```

**Comment by psantori** [comment]
Solved by PR#100
